import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { API_URL } from '../../utils/config';

export default function Orders() {
  const { token } = useAuth();
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchOrders = () => {
    fetch(`${API_URL}/orders`, {
      headers: { Authorization: `Bearer ${token}` }
    })
      .then(res => res.json())
      .then(data => {
        if (data.success && data.orders) setOrders(data.orders);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchOrders();
  }, [token]);

  const updateStatus = async (orderId, newStatus) => {
    try {
      const res = await fetch(`${API_URL}/orders/${orderId}/status`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({ status: newStatus })
      });
      const data = await res.json();
      if (data.success) {
        alert(`Order status updated to '${newStatus}'`);
        setOrders(prev => prev.map(o => o.id === orderId ? { ...o, status: newStatus } : o));
      } else {
        alert(data.message || 'Failed to update status');
      }
    } catch (err) {
      alert('Error updating order status');
    }
  };

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <div>
          <h1 style={{ fontFamily: 'Georgia, serif', fontSize: '1.8rem', color: '#2C2420', margin: 0 }}>Order Processing &amp; Status Management</h1>
          <p style={{ fontSize: '0.85rem', color: '#8C7B72', margin: '0.2rem 0 0' }}>Real-time orders generated by Customer Storefront checkouts linked to User IDs and Product IDs.</p>
        </div>
        <button 
          onClick={fetchOrders}
          style={{ padding: '0.6rem 1.2rem', background: '#7A1C2E', color: '#FFF', border: 'none', cursor: 'pointer', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.1em' }}
        >
          🔄 Refresh Orders List
        </button>
      </div>

      {loading ? (
        <div style={{ padding: '3rem', textAlign: 'center' }}>Loading live orders...</div>
      ) : orders.length === 0 ? (
        <div style={{ background: '#FFFFFF', padding: '3rem', textAlign: 'center', border: '1px solid rgba(200,169,110,0.3)' }}>
          <p style={{ fontSize: '1.1rem', color: '#2C2420', fontFamily: 'Georgia, serif', margin: 0 }}>No Customer Orders Found</p>
          <p style={{ fontSize: '0.85rem', color: '#8C7B72', margin: '0.5rem 0 0' }}>Orders placed on the storefront will appear here in real-time.</p>
        </div>
      ) : (
        <div style={{ background: '#FFFFFF', border: '1px solid rgba(200,169,110,0.25)', boxShadow: '0 4px 15px rgba(0,0,0,0.03)' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.85rem' }}>
            <thead>
              <tr style={{ background: '#FAF6F0', borderBottom: '1px solid rgba(200,169,110,0.3)', color: '#7A1C2E' }}>
                <th style={{ padding: '1rem' }}>Order ID</th>
                <th style={{ padding: '1rem' }}>Customer &amp; User ID</th>
                <th style={{ padding: '1rem' }}>Purchased Items &amp; Product IDs</th>
                <th style={{ padding: '1rem' }}>Total Amount</th>
                <th style={{ padding: '1rem' }}>Live Status</th>
                <th style={{ padding: '1rem' }}>Change Order Status</th>
              </tr>
            </thead>
            <tbody>
              {orders.map(order => (
                <tr key={order.id} style={{ borderBottom: '1px solid #FAF6F0' }}>
                  <td style={{ padding: '1rem', fontWeight: '600', fontFamily: 'monospace', color: '#7A1C2E' }}>
                    {order.id}
                  </td>

                  <td style={{ padding: '1rem' }}>
                    <div><strong>{order.customerName || order.user?.name || 'Valued Client'}</strong></div>
                    <div style={{ fontSize: '0.75rem', color: '#8C7B72' }}>{order.email || order.user?.email}</div>
                    <div style={{ fontSize: '0.7rem', color: '#C8A96E', fontFamily: 'monospace', marginTop: '0.2rem' }}>
                      User ID: {order.userId}
                    </div>
                  </td>

                  <td style={{ padding: '1rem' }}>
                    {(order.items || []).map((it, idx) => (
                      <div key={idx} style={{ marginBottom: '0.3rem' }}>
                        <div><strong>{it.name}</strong> (x{it.quantity})</div>
                        <div style={{ fontSize: '0.7rem', color: '#8C7B72', fontFamily: 'monospace' }}>
                          Product ID: {it.productId}
                        </div>
                      </div>
                    ))}
                  </td>

                  <td style={{ padding: '1rem', fontWeight: '600', fontFamily: 'Georgia, serif', fontSize: '1.05rem', color: '#2C2420' }}>
                    ₹{Number(order.totalAmount).toLocaleString('en-IN')}
                  </td>

                  <td style={{ padding: '1rem' }}>
                    <span style={{
                      padding: '0.3rem 0.7rem',
                      borderRadius: '3px',
                      fontSize: '0.75rem',
                      fontWeight: '600',
                      background: order.status === 'DELIVERED' ? '#d4efdf' : order.status === 'SHIPPED' ? '#d6eaf8' : order.status === 'IN_PROCESS' ? '#fcf3cf' : '#fadbd8',
                      color: order.status === 'DELIVERED' ? '#196f3d' : order.status === 'SHIPPED' ? '#1b4f72' : order.status === 'IN_PROCESS' ? '#7d6608' : '#78281f'
                    }}>
                      {order.status}
                    </span>
                  </td>

                  <td style={{ padding: '1rem' }}>
                    <select 
                      value={order.status} 
                      onChange={(e) => updateStatus(order.id, e.target.value)}
                      style={{ padding: '0.5rem', fontSize: '0.75rem', border: '1.5px solid #C8A96E', background: '#FAF6F0', fontWeight: '500', borderRadius: '3px', cursor: 'pointer' }}
                    >
                      <option value="PENDING">PENDING</option>
                      <option value="IN_PROCESS">IN_PROCESS</option>
                      <option value="SHIPPED">SHIPPED</option>
                      <option value="DELIVERED">DELIVERED</option>
                    </select>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
